const mongoose = require("mongoose");
const {ObjectId} = mongoose.Schema; 
const Schema = mongoose.Schema;

const orderSchema  = new Schema ({
    _id: mongoose.Schema.Types.ObjectId,
    BuyerEmail:{
        type:String
    },
    AmazonOrderId:{
        type:String,
        unique:true
    },
    EarliestDeliveryDate:{
        type:String,
        required:false
    },
    EarliestShipDate:{
        type:String,
        required:false
    },
    SalesChannel:{
        type:String,
        required:false
    },
    HasAutomatedShippingSettings:{
        type:String,
        required:false
    },
    OrderStatus:{
        type:String,
        required:false
    },
    IsPremiumOrder:{
        type:Boolean,
        required:false
    },
    IsPrime:{
        type:Boolean,
        required:false
    },
    FulfillmentChannel:{
        type:String,
        required:false
    },
    NumberOfItemsUnshipped:{
        type:Number,
        required:false
    },
    HasRegulatedItems:{
        type:Boolean,
        required:false
    },
    IsReplacementOrder:{
        type:String,
        required:false
    },
    IsSoldByAB:{
        type:Boolean,
        required:false
    },
    LatestShipDate:{
        type:String,
        required:false
    },
    ShipServiceLevel:{
        type:String,
        required:false
    },
    DefaultShipFromLocAddressLine2:{
        type:String,
        required:false
    },
    DefaultShipFromLocStateOrRegion:{
        type:String,
        required:false
    },
    DefaultShipFromLocAddressLine1:{
        type:String,
        required:false
    },
    DefaultShipFromLocPostalCode:{
        type:String,
        required:false
    },
    DefaultShipFromLocCity:{
        type:String,
        required:false
    },
    DefaultShipFromLocCountryCode:{
        type:String,
        required:false
    },
    DefaultShipFromLocName:{
        type:String,
        required:false
    },
    IsISPU:{
        type:Boolean,
        required:false
    },
    MarketplaceId:{
        type:String,
        required:false
    },
    LatestDeliveryDate:{
        type:String,
        required:false
    },
    ShippingAddressStateOrRegion:{
        type:String,
        required:false
    },
    ShippingAddressPostalCode:{
        type:String,
        required:false
    },
    ShippingAddressCity:{
        type:String,
        required:false
    },
    ShippingAddressCountryCode:{
        type:String,
        required:false
    },
    IsAccessPointOrder:{
        type:Boolean,
        required:false
    },
    PaymentMethod:{
        type:String,
        required:false
    },
    IsBusinessOrder:{
        type:Boolean,
        required:false
    },
    OrderTotalCurrencyCode:{
        type:String,
        required:false
    },
    OrderTotalAmount:{
        type:String,
        required:false
    },
    EasyShipShipmentStatus:{
        type:String,
        required:false
    },
    IsGlobalExpressEnabled:{
        type:Boolean,
        required:false
    },
    PurchaseDate:{
        type:String,
        required:false
    },
    PurchaseTime:{
        type:String,
        required:false
    },
    LastUpdateDate:{
        type:String,
        required:false
    },
    ShipmentServiceLevelCategory:{
        type:String,
        required:false
    },
    CustomerId:{
        type:String,
        required:false
    },
    isActive:{
        type:Boolean,
        required:true,
        default:true
    },
    isDelete:{
        type:Boolean,
        default:false        
    }
});


const Order = mongoose.model("order", orderSchema);
module.exports = Order;